/**
 * A pure authorization boundary for the separately governed SET execution
 * wallet.  This module only evaluates a normalized intent.  It has no signer,
 * provider, network, or transaction-submission dependency by design.
 */

export const executionRails = ["onchain", "mpp", "card", "bank"] as const;
export type ExecutionRail = (typeof executionRails)[number];

export const approvalTiers = ["A", "B", "C", "D"] as const;
export type ApprovalTier = (typeof approvalTiers)[number];

export type PurposeRule = {
  purpose: string;
  tier: ApprovalTier;
};

export type AmountLimit = {
  asset: string;
  amount: string;
};

export type ApprovedContract = {
  address: string;
  network: string;
  method: string;
};

export type ExecutionDestination =
  | { kind: "recipient"; id: string }
  | { kind: "contract"; address: string; network: string; method: string };

export type ExecutionIntent = {
  /** Opaque, one-time identifier generated by the application. */
  intentId: string;
  /** SET-owned capital reference; customer funds and wallets are not valid. */
  capitalOwner: string;
  /** The narrowly scoped signer/service authority named by the policy. */
  signingAuthority: string;
  purpose: string;
  rail: ExecutionRail;
  asset: string;
  maximumAmount: string;
  destination: ExecutionDestination;
  /** Required for onchain intents and matched against the policy allowlist. */
  network?: string;
  validAfter: string;
  expiresAt: string;
  policyVersion: string;
  /** Stable business-operation key; it is distinct from intentId. */
  idempotencyKey: string;
};

export type ApprovalEvidence = {
  approverId: string;
  intentId: string;
  policyVersion: string;
  approvedAt: string;
};

export type ExecutionPolicy = {
  /** Immutable version identifier included in every intent. */
  policyVersion: string;
  capitalOwner: string;
  signingAuthority: string;
  approvedRails: readonly ExecutionRail[];
  approvedAssets: readonly string[];
  approvedNetworks: readonly string[];
  approvedRecipients: readonly string[];
  approvedContracts: readonly ApprovedContract[];
  purposes: readonly PurposeRule[];
  limits: {
    perTransaction: readonly AmountLimit[];
    daily: readonly AmountLimit[];
    monthly: readonly AmountLimit[];
  };
  approvalTiers: Readonly<Record<ApprovalTier, { requiredApprovals: number }>>;
};

/**
 * Runtime facts supplied by the transaction service.  They are deliberately
 * not inferred here: omitted facts are UNKNOWN and therefore deny.
 */
export type ExecutionEvaluationContext = {
  now: string;
  fundsOwnershipVerified: boolean;
  signerHealthy: boolean;
  providerHealthy: boolean;
  simulationPassed: boolean;
  incidentHoldActive: boolean;
  dailySpent: readonly AmountLimit[];
  monthlySpent: readonly AmountLimit[];
  consumedIntentIds: readonly string[];
  consumedIdempotencyKeys: readonly string[];
  approvals: readonly ApprovalEvidence[];
};

export type PolicyReason = {
  code: string;
  message: string;
};

export type PolicyEvaluation = {
  allowed: boolean;
  requiredTier?: ApprovalTier;
  reasons: readonly PolicyReason[];
};

const amountPattern = /^(?:0|[1-9]\d*)(?:\.\d{1,18})?$/;

function identifier(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0 ? value.trim() : null;
}

function normalized(value: unknown): string | null {
  const found = identifier(value);
  return found === null ? null : found.toLowerCase();
}

function timestamp(value: unknown): number | null {
  const found = identifier(value);
  if (found === null) return null;
  const parsed = Date.parse(found);
  return Number.isFinite(parsed) ? parsed : null;
}

function decimal(value: unknown): { units: bigint; scale: number } | null {
  if (typeof value !== "string" || !amountPattern.test(value)) return null;
  const [whole, fraction = ""] = value.split(".");
  return { units: BigInt(`${whole}${fraction}`), scale: fraction.length };
}

function compareAmounts(left: string, right: string): number | null {
  const parsedLeft = decimal(left);
  const parsedRight = decimal(right);
  if (parsedLeft === null || parsedRight === null) return null;
  const scale = Math.max(parsedLeft.scale, parsedRight.scale);
  const leftUnits = parsedLeft.units * 10n ** BigInt(scale - parsedLeft.scale);
  const rightUnits = parsedRight.units * 10n ** BigInt(scale - parsedRight.scale);
  return leftUnits < rightUnits ? -1 : leftUnits > rightUnits ? 1 : 0;
}

function addAmounts(left: string, right: string): string | null {
  const parsedLeft = decimal(left);
  const parsedRight = decimal(right);
  if (parsedLeft === null || parsedRight === null) return null;
  const scale = Math.max(parsedLeft.scale, parsedRight.scale);
  const units = parsedLeft.units * 10n ** BigInt(scale - parsedLeft.scale) +
    parsedRight.units * 10n ** BigInt(scale - parsedRight.scale);
  const raw = units.toString().padStart(scale + 1, "0");
  if (scale === 0) return raw;
  return `${raw.slice(0, -scale)}.${raw.slice(-scale)}`.replace(/\.0+$/, "").replace(/(\.\d*?)0+$/, "$1");
}

function limitFor(asset: string, limits: readonly AmountLimit[]): AmountLimit | null {
  const matching = limits.filter((limit) => limit !== null && typeof limit === "object" && normalized(limit.asset) === normalized(asset));
  return matching.length === 1 ? matching[0] ?? null : null;
}

function unknownCode(field: string): string {
  return `UNKNOWN_${field.replace(/[A-Z]/g, (letter) => `_${letter}`).toUpperCase()}`;
}

function validPolicy(policy: ExecutionPolicy, reasons: PolicyReason[]): void {
  if (identifier(policy.policyVersion) === null) reasons.push({ code: "UNKNOWN_POLICY_VERSION", message: "Policy version is unknown." });
  if (identifier(policy.capitalOwner) === null) reasons.push({ code: "UNKNOWN_CAPITAL_OWNER", message: "Capital owner is unknown." });
  if (identifier(policy.signingAuthority) === null) reasons.push({ code: "UNKNOWN_SIGNING_AUTHORITY", message: "Signing authority is unknown." });
  if (!Array.isArray(policy.approvedRails)) reasons.push({ code: "UNKNOWN_APPROVED_RAILS", message: "Approved rails are unknown." });
  if (!Array.isArray(policy.approvedAssets)) reasons.push({ code: "UNKNOWN_APPROVED_ASSETS", message: "Approved assets are unknown." });
  if (!Array.isArray(policy.approvedNetworks)) reasons.push({ code: "UNKNOWN_APPROVED_NETWORKS", message: "Approved networks are unknown." });
  if (!Array.isArray(policy.approvedRecipients)) reasons.push({ code: "UNKNOWN_APPROVED_RECIPIENTS", message: "Approved recipients are unknown." });
  if (!Array.isArray(policy.approvedContracts)) reasons.push({ code: "UNKNOWN_APPROVED_CONTRACTS", message: "Approved contracts are unknown." });
  if (!Array.isArray(policy.purposes)) reasons.push({ code: "UNKNOWN_PURPOSE_REGISTRY", message: "Purpose registry is unknown." });
  if (!policy.limits || !Array.isArray(policy.limits.perTransaction) || !Array.isArray(policy.limits.daily) || !Array.isArray(policy.limits.monthly)) {
    reasons.push({ code: "UNKNOWN_LIMITS", message: "Transaction, daily, or monthly limits are unknown." });
  }
  if (!policy.approvalTiers) reasons.push({ code: "UNKNOWN_APPROVAL_TIERS", message: "Approval tiers are unknown." });
}

function validContext(context: Partial<ExecutionEvaluationContext>, reasons: PolicyReason[]): context is ExecutionEvaluationContext {
  const requiredBooleans = ["fundsOwnershipVerified", "signerHealthy", "providerHealthy", "simulationPassed", "incidentHoldActive"] as const;
  for (const field of requiredBooleans) {
    if (typeof context[field] !== "boolean") reasons.push({ code: unknownCode(field), message: `${field} evidence is unknown.` });
  }
  for (const field of ["now", "dailySpent", "monthlySpent", "consumedIntentIds", "consumedIdempotencyKeys", "approvals"] as const) {
    if (field === "now" ? timestamp(context[field]) === null : !Array.isArray(context[field])) {
      reasons.push({ code: unknownCode(field), message: `${field} evidence is unknown.` });
    }
  }
  return reasons.length === 0;
}

/**
 * Deterministically evaluates an intent.  This function only returns a
 * decision; it cannot sign, submit, or otherwise cause a transaction.
 */
export function evaluate(
  policy: ExecutionPolicy,
  intent: Partial<ExecutionIntent>,
  context: Partial<ExecutionEvaluationContext> = {}
): PolicyEvaluation {
  const reasons: PolicyReason[] = [];
  validPolicy(policy, reasons);
  validContext(context, reasons);
  const approvedRails = Array.isArray(policy.approvedRails) ? policy.approvedRails : [];
  const approvedAssets = Array.isArray(policy.approvedAssets) ? policy.approvedAssets : [];
  const approvedNetworks = Array.isArray(policy.approvedNetworks) ? policy.approvedNetworks : [];
  const approvedRecipients = Array.isArray(policy.approvedRecipients) ? policy.approvedRecipients : [];
  const approvedContracts = Array.isArray(policy.approvedContracts) ? policy.approvedContracts : [];
  const purposes = Array.isArray(policy.purposes) ? policy.purposes : [];
  const perTransactionLimits = Array.isArray(policy.limits?.perTransaction) ? policy.limits.perTransaction : [];
  const dailyLimits = Array.isArray(policy.limits?.daily) ? policy.limits.daily : [];
  const monthlyLimits = Array.isArray(policy.limits?.monthly) ? policy.limits.monthly : [];

  const intentId = identifier(intent.intentId);
  const owner = identifier(intent.capitalOwner);
  const authority = identifier(intent.signingAuthority);
  const purpose = identifier(intent.purpose);
  const asset = normalized(intent.asset);
  const policyVersion = identifier(intent.policyVersion);
  const idempotencyKey = identifier(intent.idempotencyKey);
  const maximumAmount = typeof intent.maximumAmount === "string" ? intent.maximumAmount : null;
  const rail = normalized(intent.rail);

  if (intentId === null) reasons.push({ code: "UNKNOWN_INTENT_ID", message: "Replay-resistant intent ID is unknown." });
  if (owner === null) reasons.push({ code: "UNKNOWN_CAPITAL_OWNER", message: "Intent capital owner is unknown." });
  if (authority === null) reasons.push({ code: "UNKNOWN_SIGNING_AUTHORITY", message: "Intent signing authority is unknown." });
  if (purpose === null) reasons.push({ code: "UNKNOWN_PURPOSE", message: "Intent purpose is unknown." });
  if (asset === null) reasons.push({ code: "UNKNOWN_ASSET", message: "Intent asset is unknown." });
  if (maximumAmount === null || decimal(maximumAmount) === null) reasons.push({ code: "INVALID_AMOUNT", message: "Maximum amount is unknown or invalid." });
  if (maximumAmount !== null && decimal(maximumAmount) !== null && compareAmounts(maximumAmount, "0") === 0) reasons.push({ code: "INVALID_AMOUNT", message: "Maximum amount must be greater than zero." });
  if (policyVersion === null) reasons.push({ code: "UNKNOWN_POLICY_VERSION", message: "Intent policy version is unknown." });
  if (idempotencyKey === null) reasons.push({ code: "UNKNOWN_IDEMPOTENCY_KEY", message: "Replay-resistant idempotency key is unknown." });
  if (rail === null || !executionRails.includes(rail as ExecutionRail)) reasons.push({ code: "UNKNOWN_RAIL", message: "Intent rail is unknown or unsupported." });

  const destination = intent.destination;
  const validDestination = destination !== undefined && destination !== null && typeof destination === "object" &&
    (destination.kind === "recipient" || destination.kind === "contract");
  if (!validDestination) reasons.push({ code: "UNKNOWN_DESTINATION", message: "Recipient or contract destination is unknown." });

  const validAfter = timestamp(intent.validAfter);
  const expiresAt = timestamp(intent.expiresAt);
  const now = timestamp(context.now);
  if (validAfter === null || expiresAt === null || now === null) {
    reasons.push({ code: "UNKNOWN_VALIDITY_WINDOW", message: "Intent validity window is unknown." });
  } else {
    if (expiresAt <= validAfter) reasons.push({ code: "INVALID_VALIDITY_WINDOW", message: "Intent expiry must be after valid-after." });
    if (now < validAfter) reasons.push({ code: "NOT_YET_VALID", message: "Intent is not yet valid." });
    if (now >= expiresAt) reasons.push({ code: "EXPIRED", message: "Intent has expired." });
  }

  let requiredTier: ApprovalTier | undefined;
  const purposeRule = purpose === null ? undefined : purposes.filter((rule) => rule !== null && typeof rule === "object" && rule.purpose === purpose);
  if (!purposeRule || purposeRule.length !== 1) {
    reasons.push({ code: "PURPOSE_NOT_ALLOWLISTED", message: "Purpose is not uniquely allowlisted." });
  } else {
    requiredTier = purposeRule[0]?.tier;
    if (!approvalTiers.includes(requiredTier as ApprovalTier)) reasons.push({ code: "UNKNOWN_APPROVAL_TIER", message: "Purpose approval tier is unknown." });
  }

  if (owner !== null && identifier(policy.capitalOwner) !== owner) reasons.push({ code: "CAPITAL_OWNER_MISMATCH", message: "Intent capital owner does not match the policy owner." });
  if (authority !== null && identifier(policy.signingAuthority) !== authority) reasons.push({ code: "SIGNING_AUTHORITY_MISMATCH", message: "Intent signing authority does not match the policy authority." });
  if (policyVersion !== null && identifier(policy.policyVersion) !== policyVersion) reasons.push({ code: "POLICY_VERSION_MISMATCH", message: "Intent policy version does not match the installed policy." });
  if (asset !== null && !approvedAssets.some((value) => normalized(value) === asset)) reasons.push({ code: "ASSET_NOT_ALLOWLISTED", message: "Asset is not allowlisted." });
  if (rail !== null && executionRails.includes(rail as ExecutionRail) && !approvedRails.some((value) => value === rail)) reasons.push({ code: "RAIL_NOT_ALLOWLISTED", message: "Rail is not allowlisted." });

  const network = normalized(intent.network);
  if (rail === "onchain" && network === null) reasons.push({ code: "UNKNOWN_NETWORK", message: "Onchain network is unknown." });
  if (network !== null && !approvedNetworks.some((value) => normalized(value) === network)) reasons.push({ code: "NETWORK_NOT_ALLOWLISTED", message: "Network is not allowlisted." });
  if (rail !== "onchain" && network !== null) reasons.push({ code: "UNEXPECTED_NETWORK", message: "Non-onchain intent must not add an ungoverned network." });

  if (validDestination && destination !== undefined) {
    if (destination.kind === "recipient") {
      if (!approvedRecipients.includes(destination.id)) reasons.push({ code: "RECIPIENT_NOT_ALLOWLISTED", message: "Recipient is not allowlisted." });
    } else {
      const contract = destination;
      const matched = approvedContracts.some((allowed) => allowed !== null && typeof allowed === "object" && allowed.address === contract.address &&
        normalized(allowed.network) === normalized(contract.network) && allowed.method === contract.method);
      if (!matched) reasons.push({ code: "CONTRACT_NOT_ALLOWLISTED", message: "Contract address, network, and method are not allowlisted." });
      if (network !== null && network !== normalized(contract.network)) reasons.push({ code: "NETWORK_DESTINATION_MISMATCH", message: "Intent network does not match the contract network." });
    }
  }

  const perTransaction = asset === null ? null : limitFor(asset, perTransactionLimits);
  const daily = asset === null ? null : limitFor(asset, dailyLimits);
  if (perTransaction === null || decimal(perTransaction.amount) === null) reasons.push({ code: "UNKNOWN_TRANSACTION_LIMIT", message: "A unique per-transaction limit is unknown." });
  if (daily === null || decimal(daily.amount) === null) reasons.push({ code: "UNKNOWN_DAILY_LIMIT", message: "A unique daily limit is unknown." });
  if (maximumAmount !== null && perTransaction !== null && compareAmounts(maximumAmount, perTransaction.amount)! > 0) reasons.push({ code: "TRANSACTION_LIMIT_EXCEEDED", message: "Maximum amount exceeds the per-transaction limit." });

  const spent = asset === null ? null : limitFor(asset, context.dailySpent ?? []);
  if (spent === null) reasons.push({ code: "UNKNOWN_DAILY_SPEND", message: "Current daily spend is unknown." });
  if (maximumAmount !== null && daily !== null && spent !== null) {
    const total = addAmounts(maximumAmount, spent.amount);
    if (total === null || compareAmounts(total, daily.amount)! > 0) reasons.push({ code: "DAILY_LIMIT_EXCEEDED", message: "Intent plus current daily spend exceeds the daily limit." });
  }

  const monthly = asset === null ? null : limitFor(asset, monthlyLimits);
  if (monthly === null || decimal(monthly.amount) === null) reasons.push({ code: "UNKNOWN_MONTHLY_LIMIT", message: "A unique monthly limit is unknown." });
  const monthlySpent = asset === null ? null : limitFor(asset, context.monthlySpent ?? []);
  if (monthlySpent === null) reasons.push({ code: "UNKNOWN_MONTHLY_SPEND", message: "Current monthly spend is unknown." });
  if (maximumAmount !== null && monthly !== null && monthlySpent !== null) {
    const total = addAmounts(maximumAmount, monthlySpent.amount);
    if (total === null || compareAmounts(total, monthly.amount)! > 0) reasons.push({ code: "MONTHLY_LIMIT_EXCEEDED", message: "Intent plus current monthly spend exceeds the monthly limit." });
  }

  const spendEvidence = [
    ["daily", context.dailySpent],
    ["monthly", context.monthlySpent]
  ] as const;
  for (const [period, entries] of spendEvidence) {
    if (!Array.isArray(entries)) continue;
    if (entries.some((entry) => entry === null || typeof entry !== "object" ||
      identifier(entry.asset) === null || decimal(entry.amount) === null)) {
      reasons.push({ code: `INVALID_${period.toUpperCase()}_SPEND`, message: `At least one ${period} spend record is malformed.` });
    }
  }

  if (intentId !== null && context.consumedIntentIds?.includes(intentId)) reasons.push({ code: "INTENT_REPLAYED", message: "Intent ID has already been consumed." });
  if (idempotencyKey !== null && context.consumedIdempotencyKeys?.includes(idempotencyKey)) reasons.push({ code: "IDEMPOTENCY_REPLAYED", message: "Idempotency key has already been consumed." });
  if (intentId !== null && idempotencyKey !== null && intentId === idempotencyKey) reasons.push({ code: "NON_DISTINCT_REPLAY_KEYS", message: "Intent ID and idempotency key must be distinct." });
  if (context.fundsOwnershipVerified !== true) reasons.push({ code: "FUNDS_OWNERSHIP_UNVERIFIED", message: "Capital ownership evidence is not verified." });
  if (context.signerHealthy !== true) reasons.push({ code: "SIGNER_UNHEALTHY", message: "Signer health is not verified." });
  if (context.providerHealthy !== true) reasons.push({ code: "PROVIDER_UNHEALTHY", message: "Provider health is not verified." });
  if (context.simulationPassed !== true) reasons.push({ code: "SIMULATION_NOT_PASSED", message: "Transaction simulation has not passed." });
  if (context.incidentHoldActive !== false) reasons.push({ code: "INCIDENT_HOLD", message: "An incident hold is active or unknown." });

  if (requiredTier === "D") reasons.push({ code: "PROHIBITED_TIER", message: "Tier D intents are prohibited." });
  const tierConfig = requiredTier === undefined ? undefined : policy.approvalTiers?.[requiredTier];
  if (requiredTier !== undefined && (!tierConfig || !Number.isInteger(tierConfig.requiredApprovals) || tierConfig.requiredApprovals < 0)) {
    reasons.push({ code: "UNKNOWN_APPROVAL_REQUIREMENT", message: "Approval requirement is unknown." });
  } else if (requiredTier !== undefined && tierConfig && requiredTier !== "D") {
    const approvals = context.approvals ?? [];
    if (approvals.some((approval) => approval === null || typeof approval !== "object" ||
      identifier(approval.approverId) === null || identifier(approval.intentId) === null ||
      identifier(approval.policyVersion) === null || timestamp(approval.approvedAt) === null)) {
      reasons.push({ code: "INVALID_APPROVALS", message: "At least one approval record is malformed." });
    }
    const uniqueApprovers = new Set(approvals
      .filter((approval) => approval.intentId === intentId && approval.policyVersion === policyVersion)
      .filter((approval) => {
        const approvedAt = timestamp(approval.approvedAt);
        if (approvedAt === null || validAfter === null || expiresAt === null || now === null) return false;
        if (approvedAt < validAfter || approvedAt >= expiresAt) {
          reasons.push({ code: "APPROVAL_OUTSIDE_VALIDITY_WINDOW", message: "Approval was recorded outside the intent validity window." });
          return false;
        }
        if (approvedAt > now) {
          reasons.push({ code: "APPROVAL_NOT_YET_VALID", message: "Approval timestamp is later than the evaluation time." });
          return false;
        }
        return true;
      })
      .map((approval) => approval.approverId));
    if (uniqueApprovers.size < tierConfig.requiredApprovals) reasons.push({ code: "INSUFFICIENT_APPROVALS", message: "Required approval tier has not been satisfied." });
  }

  return { allowed: reasons.length === 0, ...(requiredTier === undefined ? {} : { requiredTier }), reasons };
}
